Yamato-Security/hayabusa-rules

config/eventkey_alias.txt
config/exclude_rules.txt
hayabusa/non-default/alerts/Security/5038-6281-6410_CodeIntegrityProblem-PossibleModification.yml
hayabusa/sysmon/alerts/6_CodeSigning_DriverLoadedWithInvalidSignature.yml
hayabusa/sysmon/alerts/6_CodeSigning_UnsignedDriverLoaded.yml

最近話題になっている流出されたNVIDIA証明証に署名されたマルウェア等を検知するため。

Rules to detect bad Windows drivers

---

.github/workflows/update-sigmarule.yml

SigmaルールをAutoUpdateする機能
Sigmaに更新があれば勝手に `rules/auto-sigma-update` にプルリクが日々作られ、マージされていく。
わざわざプルリクを作るのはその日になんのルールが追加、削除されたかわかりやすくなるから。
sample: https://github.com/Yamato-Security/hayabusa-rules/pull/5
アップデートされた`sigma-latest`ディレクトリをもとにルールの正当性を検証、よければdevelopから切ったブランチ(rules/add-sigma-xxx)にルールを追加してプルリクを作成、developにマージしていく。
```mermaid
graph LR;
sigma-latest --Create HayabusaRules-->rules/auto-sigma-update;
rules/auto-sigma-update -- Auto Merge --> sigma-latest;
sigma-latest -.- c{Rule check & create PR};
c{Rule check & create PR} -..-> rules/add-sigma-xxx;
rules/add-sigma-xxx --> develop;
develop -->main;
```
- 更新があると作られる https://github.com/Yamato-Security/hayabusa-rules/pull/5 は見やすいか
- ブランチ戦略はこれでいいか
closes #3

Github actions for update sigma rules

---

config/level_tuning.txt

https://github.com/Yamato-Security/hayabusa/pull/512 の対応で level_tuning.txtにテストファイル用の内容が入っていると--level-tuning実行時にテストファイルもチューニング対象となってしまうため削除しました

removed test rule line from level_tuning.txt

---

.github/workflows/update-sigmarule.yaml

Closes #54 
- updated create-pull-request v4
今回のpull-requestで継続してエラーが出るかを確かめたいと思います。

updated create-pull-request github action

---

config/eventkey_alias.txt

`Provider Name`が正しく定義されていませんでした。
sample-evtxに対して、
Before:
```
Unique detections: 503
```
After:
```
Unique detections: 517
```
`Channel`ではなく、`Provider Name`を使っているsigmaルールが多い(約70件)ので、検知率が大分上がるはずです。

provider name alias fix

---

config/exclude_rules.txt

there were 2 sigma rules doing the same thing as 1 hayabusa rule so I am excluding them.

update exclude rules

---

tools/sigmac/convert.py
tools/sigmac/exclude_rule_list.txt

https://github.com/Yamato-Security/hayabusa-rules/pull/92#issuecomment-1221190253 にてルール変換しない機能が欲しいとの要望に応えて実装。
exclude-rule-list に不要なルールを記載、オプション(`--exclude-rule-list <作成したリストへのパス>`)をつけると変換されなくなる。
```sh
❯ python3 convert.py -r rules/windows.bak --exclude-rule-list ../../Yamato-Security/hayabusa-rules/tools/sigmac/exclude_rule_list.txt --debug
Converting rules. Please wait.
0 rules where converted! (failed: 0)
```
Hayabusa側の [exclude_rules.txt](https://github.com/Yamato-Security/hayabusa-rules/blob/main/config/exclude_rules.txt) で実装があるためそちら側を利用するかこちらも入れるか。
機能がかぶっておりあくまでメインはHayabusaなのでconvertの機能としては変換スクリプトがどんどん汎用性のないものになってしまうためいれなくてもいいと思っている。

Add: exclude_rule_list function

---

.github/workflows/update-sigmarule.yaml

@itiB 
すいません、前回のgithub actionのファイルだと、pull requestが正しく作られない問題があるようです。原因としては既存のpull requestと同じtitleを指定した場合、新規にpull requestが作られず既存のpull requestに更新されるような動きになるようです。既存のpull requestは既にclose済みで正しくauto merge出来ていないような感じでした。
あとslackにも書いたのですが、そもそもauto mergeして良いか分かってないです。もし、auto mergeしないなら、その部分のコメントアウトした上でこのpull requestをapprove/mergeしてもらえればと思います。
closes #96

Feature/fix GitHub action

---

.github/workflows/update-sigmarule.yaml

@hach1yon 
itibさんがreviewerにアサインされているので、自動マージできないようです。
assigneesとreviewersの定義は必要ですか？
これらを無くせば、PRをチェックしなくても自動マージできるかもしれません。

unassign reviewer for auto merging

---

.github/workflows/update-sigmarule.yaml

同じ名前のブランチが関連づいているpull requestが既にあると、pull requestが新規作成されないっぽいので、とりあえずそれを回避するように変更しました。これを一旦approveして、試したいです。

enable automerge of rule update workflow

---

tools/sigmac/convert.py

- fix: #151
- fixed string concatenation in TimeoutExpired catch block.
- Python 3.10.6
- macOS Monterey version 12.6
- MacBook Air (M1, 2020)
1. [Execute the reproduction procedure described in #151](https://github.com/Yamato-Security/hayabusa-rules/issues/151#issuecomment-1279675529) (Put the two yml files in the rules directory)
2. convert.py not failed and output is as follows.
```
python3 convert.py
Converting rules. Please wait.
[ERROR   ] Timeout Expired, failed to convert ./hayabusa_rules/builtin/win_av_relevant_match.yml
Command: ['python3', './tools/sigmac', '-t', 'hayabusa', '-c', './tools/config/generic/windows-services.yml', '--defer-abort', './rules/windows/win_av_relevant_match.yml']
[ERROR   ] Timeout Expired, failed to convert ./hayabusa_rules/builtin/win_audit_cve.yml …
```

fix: convert.py fails if one rule times out

---

.github/workflows/update-sigmarule.yaml

Closes #152 
Actionをバージョンアップしたら、古いNode.jsの警告で出なくなりました。

update action versions

---

README-Japanese.md
README.md

Hayabusa now uses `Data` instead of `EventData` to check `Data` fields. The same as sigma.

update readme EventData change to Data

---

tools/sigmac/hayabusa.py

先程、Hayabusa 1.8.1でルールを更新したら、６件のパースエラーが出ていました。
調べたら、上流のSigmaリポで正規表現を直したので、変換スクリプトで`|re`の変換が悪さをしているみたいなので、正規表現をそのまま渡すようにしたいです。(1.8.1をv2のブランチでかけたら、パースエラー出ませんでした。）
以前に高橋さんが`|re`のコード修正のようにhayabusa.pyを修正してみましたが、念の為、確認をお願いできますか？

stop regex conversion

---

tools/sigmac/hayabusa.py

- fixed: #241 
- If the YAML value is `null`, do not convert it to `|re: ^$` (pass `None` as is)
- changed  output function`yaml.dump()` to `yaml.safe_dump()`  
- because `yaml.dump()` doesn't output `null` value (if passed `None`, output nothing)
- Python 3.11.0
- macOS Ventura version 13.0.1 (MacBook Air (M1, 2020))
Compared the command results below,
`python3 ./tools/sigmac -t hayabusa -c ./tools/config/generic/windows-audit.yml -c ./tools/config/generic/windows-services.yml rules/windows/process_creation/proc_creation_win_proc_wrong_parent.yml > test.yml`
diff results is as follows.
```
sigma % diff test.yml test-dev.yml
37c37
<         ParentProcessName|re: ^$
---
>         ParentProcessName: null
```
Confirmed that no unnecessary diffs before and after fix. [Here is full …

fix: keep Sigma YAML `null` value as is

---

config/generic_abbreviations.txt
config/provider_abbreviations.txt

I added config file to abbreviate provider names.
I want to use `generic_abbreviations.txt` generically for both channel and provider names so would like to delete `channel_abbreviations_generic.txt` in the future. For now will leave it there until we change things in Hayabusa.

add provider abbreviation config files

---

CHANGELOG-Japanese.md
CHANGELOG.md
tools/sigmac/convert.py

- Fixed #327 
- The specifications of the folder hierarchy are as follows.
- From: sigma/rules-deprecated 
- To: sigma/builtin/deprecated
- To: sigma/sysmon/deprecated
- From: sigma/rules-unsupported/windows
- To: sigma/builtin/unsupported
- To: sigma/sysmon/unsupported
- Hard: Macbook Air(M1, 2020) , Memory 8GB, Core 8
- Python 3.11
I confirmed that there is no difference other than the deprecated/unsupported folder before/after fix.
```
fukusuke@fukusukenoAir sigma % diff -r hayabusa_rules_new hayabusa_rules_org
Only in hayabusa_rules_new/builtin: deprecated
Only in hayabusa_rules_new/builtin: unsupported
Only in hayabusa_rules_new/sysmon: deprecated
Only in hayabusa_rules_new/sysmon: unsupported
```
I confirmed that unsupported/deprecated rules are …

feat: convert deprecated rules

---

tools/sigmac/rule.py

Changed the conversion process to keep `cidr` value as is
- Hard: Macbook Air(M1, 2020) , Memory 8GB, Core 8
rule with the `|cidr` modifier conversion succeeded as follows
```
fukusuke@fukusukenoAir sigma % python3 ./tools/sigmac -t hayabusa -c ./tools/config/generic/windows-audit.yml -c ./tools/config/generic/windows-services.yml --defer-abort ./rules/windows/builtin/security/win_security_successful_external_remote_rdp_login.yml
title: External Remote RDP Logon from Public IP
ruletype: Sigma
author: Micah Babinski, @micahbabinski
date: 2023/01/19
description: Detects successful logon from public IP address via RDP. This can indicate
a publicly-exposed RDP port.
detection:
SELECTION_1:
Channel: Security
SELECTION_2:
EventID: 4624
SELECTION_3:
LogonType: 10 …
```

feat: keep `cidr` rule value as is

---

config/exclude_rules.txt

could one of you check these?
maybe one day we can fix the regex in the rules but for now I want to ignore them.
Please merge if ok.

exclude regex parse error rules

---

.github/workflows/update-sigmarule.yaml

- Fixed: #357
- Changed sigmac tool path in githubactions
- Because sigmac moved [SigmaHQ/legacy-sigmatools](https://github.com/SigmaHQ/legacy-sigmatools) repo
- https://github.com/SigmaHQ/sigma/pull/4157
I would appreciate it if you could review🙏

Update GitHub Actions sigmac tool path

---

config/pivot_keywords.txt

Process IDs and Process GUIDs create too long of a list with too many false positives so I deleted them.

remove PIDs from pivot keywords

---

README-Japanese.md
README.md

There was no explanation for `|contains|all` so I added it.

add |contains|all explanation

---

tools/sigmac/logsource_mapping.py

- Added support for `|all`(no-field) modifier rules
- Related PR:  https://github.com/Yamato-Security/hayabusa/pull/1060
- Python 3.11.1
I confirmed that `logsource_mapping.py` completes successfully as follows.(`ERROR` is expected behavior)
```
[INFO:logsource_mapping.py:323] Start to logsource mapping sigma rules.
[INFO:logsource_mapping.py:355] Loading logsource mapping yaml(sysmon/windows-audit/windows-services) done.
[INFO:logsource_mapping.py:302] Start to collect target yml files path.
[ERROR:logsource_mapping.py:318] Error while loading yml [../../../sigma/unsupported/windows/win_apt_apt29_tor.yml]: expected a single document in the stream
in …
```

chg: add support for `|all`(no-field) modifier rule

---

hayabusa/builtin/WindowsDefender/Defender_1116_Crit_Alert.yml
hayabusa/builtin/WindowsDefender/Defender_1116_High_Alert.yml
hayabusa/builtin/WindowsDefender/Defender_1116_Low_Alert.yml
hayabusa/builtin/WindowsDefender/Defender_1116_Med_Alert.yml
hayabusa/sysmon/Sysmon_22_Med_DNS-Query_RuleAlert.yml

Some rules had duplicate keys as follows, so I deleted them.
(For example, the `logsource` is duplicated in the example below.)
```
id: 810bfd3a-9fb3-44e0-9016-8cdf785fddbf
level: critical
status: test
logsource:
product: windows
service: windefend
detection:
selection:
Channel: Microsoft-Windows-Windows Defender/Operational
EventID: 1116
SeverityID: 5 # Severe
falsepositives:
- bad signature
tags:
- malware
references:
- https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshoot-microsoft-defender-antivirus?view=o365-worldwide
logsource: default
ruletype: Hayabusa
```
I would appreciate it if you could review🙏

refactor: remove duplicated keys in yml

---

tools/sigmac/logsource_mapping.py

- Fixed #453 
- Added process for adding `sysmon` tag when logsource is `sysmon`
- Python 3.11.1
I confirmed that `logsource` == `sysmon` are tagged.
[proc_creation_win_conhost_uncommon_parent.yml](https://github.com/SigmaHQ/sigma/blob/c0332a9d96f6c7804fcc85dd706caed889446a62/rules/windows/process_creation/proc_creation_win_conhost_uncommon_parent.yml#L2)
`logsource_mapping.py`'s output rule is as follows.
```
title: Conhost Spawned By Uncommon Parent Process
id: cbb9e3d1-2386-4e59-912e-62f1484f7a89
status: experimental
description: Detects when the Console Window Host (conhost.exe) process is spawned
by an uncommon parent process, which could be indicative of potential code injection
activity.
references: …
```

feat: add `sysmon` tag when logsource service is `sysmon`

---

sigma/builtin/category/antivirus/av_exploiting.yml
sigma/builtin/category/antivirus/av_hacktool.yml
sigma/builtin/category/antivirus/av_password_dumper.yml
sigma/builtin/category/antivirus/av_printernightmare_cve_2021_34527.yml
sigma/builtin/category/antivirus/av_ransomware.yml
sigma/builtin/category/antivirus/av_relevant_files.yml
sigma/builtin/category/antivirus/av_webshell.yml
tools/sigmac/logsource_mapping.py
tools/sigmac/windows-antivirus.yml

- Fixed #456
- Added process for conversion  `antivirus category` rule
- Python 3.11.1
[av_exploiting.yml](https://github.com/SigmaHQ/sigma/blob/c0332a9d96f6c7804fcc85dd706caed889446a62/rules/category/antivirus/av_exploiting.yml#L1) is converted as follows. (`Signature` -> `ThreatName`)
```
title: Antivirus Exploitation Framework Detection
id: 238527ad-3c2c-4e4f-a1f6-92fd63adb864
status: stable
description: Detects a highly relevant Antivirus alert that reports an exploitation
framework
references:
- https://www.nextron-systems.com/?s=antivirus
- https://www.virustotal.com/gui/file/925b0b28472d4d79b4bf92050e38cc2b8f722691c713fc28743ac38551bc3797
- …
```

feat: add `antivirus` category conversion

---

hayabusa/builtin/Partition_Diagnostic/PartitionDiagnostic_1006_Info_DeviceConn.yml

- added partition diagnostic rule
-  related https://github.com/Yamato-Security/takajo/issues/67
- OS: macOS sonoma version 14.0
- Hayabusa 2.10.1
```
2023-11-17 13:06:47.048 +09:00 ‖ mouse ‖ MS-Win-Partition/Diagnostic ‖ 1006 ‖ info ‖ 51 ‖ Device Conn ‖ Manufacturer: NVMe ¦ Model: KINGSTON OM8PDP3512B-A01 ¦ Revision: EDFK0S03 ¦ SerialNumber: 0026_B768_5D25_0F85. ‖ Adapter: 0 ¦ AdapterAlignmentMask: 3 ¦ AdapterId: A9786D92-695A-11EE-BDC1-806E6F6E6963 ¦ AdapterMaximumTransferBytes: 131072 ¦ AdapterMaximumTransferPages: 33 ¦ AdapterSerialNumber: NULL ¦ Bus: 0 ¦ BusType: 17 ¦ BytesOffsetForSectorAlignment: 0 ¦ BytesPerLogicalSector: 512 ¦ BytesPerPhysicalSector: 512 ¦ BytesPerSector: 512 ¦ Capacity: 512110190592 ¦ Characteristics: 256 ¦ …
```

feat: add partition diagnostic rule

---

.github/workflows/rule-parse-error-check.yaml

- feat: #520 
- Added GitHub Actions for rule parse error check
-  If the return value of the following command is not 0, make PullRequest an error. 
- `cd hayabusa && cargo run --release -- csv-timeline -d ../hayabusa-sample-evtx -r ../hayabusa-rules -w -o timeline.csv  | grep "Rule parsing error" | wc -l | grep 0`
- This action is triggered by the creation of a Pull Request
I have confirmed the following behavior in my repository.
- parse error
- https://github.com/fukusuket/hayabusa-rules/actions/runs/7211316237/job/19646467384
- parse success
- https://github.com/fukusuket/hayabusa-rules/actions/runs/7211308393/job/19646440672

feat: add rule parse error check GitHub Actions

---

config/default_details.txt
hayabusa/sysmon/Sysmon_13_RegKeyValueSet_RuleAlert.yml

Closes https://github.com/Yamato-Security/hayabusa/issues/1229

fix broken pipe typo

---

.github/workflows/rule-parse-error-check.yaml
.github/workflows/update-sigmarule.yaml

- Fixed #520
- Run rule parsing error checking before automatic PR creation actions as follows
- Download latest hayabusa release binary  
- Run csv-timeline command
- Check `Rule parsing error` message  in console
- The above checks are done before automatic PR creation
- If the check fails, do not create automatic PR
if rule `rule-parse-error-check` is `true`
- https://github.com/Yamato-Security/hayabusa-rules/actions/runs/7601027408
if rule `rule-parse-error-check` is `false`
- https://github.com/Yamato-Security/hayabusa-rules/actions/runs/7601048022

fix: add rule parse error check for auto PR

---

.github/workflows/update-sigmarule.yaml

- Related #580 
- I noticed that the above PR action checks the rules **after merging the previous PR** ...
- As a result, the incorrect rule was **merged once**, and the parsing error was **found in the second PR**.
- This PR has been fixed so that parse errors can be detected **before merging**.
As shown below, rule-parse-error-check has been modified to check for parse errors after converting the latest Sigma rule.
- https://github.com/Yamato-Security/hayabusa-rules/actions/runs/7612852965
I apologize for the inconvenience... 🙇

feat: check for parse errors before creating PR

---

.github/workflows/update-sigmarule.yaml

- Related #583
-  changed required option to true
AutoPR was working in check false mode...so I changed the required option to true.
Manually PR (`run csv-timeline` executed)
https://github.com/Yamato-Security/hayabusa-rules/actions/runs/7631251042/job/20788784777
Auto PR(`run csv-timeline` **not** executed)
https://github.com/Yamato-Security/hayabusa-rules/actions/runs/7617479708/job/20746564662
Sorry...I don't know if this will solve the problem, but could you please merge it once?🙏

fix: changed  rule parse check error option required to true

---

.github/workflows/update-sigmarule.yaml

Changed `rule-parse-error-check` -> `disable-rule-parse-error-check`
- Related #588
- Related #583
Sorry... it seems that neither of the above fixes had any effect.
The default value of the bool value seems to be `false`, so I changed the flag so that it defaults to `false`.
default(disable-rule-parse-error-check=false) `run-csv` executed as follows.
https://github.com/Yamato-Security/hayabusa-rules/actions/runs/7711076080/job/21015714517
check on(disable-rule-parse-error-check=true) `run-csv` not executed as follows.
https://github.com/Yamato-Security/hayabusa-rules/actions/runs/7711082373/job/21015733818
I would appreciate it if you could merge it🙏

fix: reverse GitHub actions rule-parse-error-check flag

---

tools/sigmac/logsource_mapping.py
tools/sigmac/test_logsource_mapping.py

- Closed #605 
- This is because the expected value of the test was not changed when the category was changed in the issue below.
- https://github.com/Yamato-Security/hayabusa-rules/pull/596
I confirmed that all unit tests pass as shown below.
```
% python -m unittest
................
----------------------------------------------------------------------
Ran 16 tests in 0.304s
OK
```

test: fix failing unittest

---

config/default_details.txt

- Closed #616
- Closed #617
`% ./hayabusa json-timeline -d ../all-evtx/Win2022-AD -m high -o out.json -w -C --include-eid
13`
```json
{
"Timestamp": "2022-04-07 17:14:49.824 +09:00",
"RuleTitle": "Disable Windows Defender Functionalities Via Registry Keys",
"Level": "high",
"Computer": "WIN-FPV0DSIC9O6.sigma.fr",
"Channel": "Sysmon",
"EventID": 13,
"RecordID": 160653,
"Details": {
"EventType": "SetValue",
"TgtObj": "HKLM\\SOFTWARE\\Microsoft\\Windows Defender\\Features\\TamperProtection",
"Details": "DWORD (0x00000000)",
"Proc": "C:\\Program Files\\Windows Defender\\MsMpEng.exe",
"PID": 2936,
"PGUID": "CB66FCBA-9D71-624E-4700-000000000200"
},
"ExtraFieldInfo": {
"RuleName": "-",
"User": "NT AUTHORITY\\SYSTEM",
"UtcTime": "2022-04-07 08:14:49.818"
}
}
```
`% ./hayabusa json-timeline -d …

fix: add field name to default_detail.txt (Sysmon EID 13, 14)

---

hayabusa/builtin/WindowsDefender/Defender_1116_Crit_Alert.yml
hayabusa/builtin/WindowsDefender/Defender_1116_High_Alert.yml
hayabusa/builtin/WindowsDefender/Defender_1116_Low_Alert.yml
hayabusa/builtin/WindowsDefender/Defender_1116_Med_Alert.yml

There was no `condition` clause in the Windows Defender rules, so I added it.
- Related: https://github.com/Velocidex/velociraptor-sigma-rules/issues/24#issuecomment-2008651738
For some reason, Hayabusa seems to be able to detect it even if there is no `condition` clause... :)

fix: add condition clause in Windows Defender rule

---

.github/workflows/rule-parse-error-check.yaml

The file naming convention for hayabusa release binaries has changed and actions are failing, so we fixed it.

fix: update GitHub action's hayabusa zip name

---

.github/workflows/rule-parse-error-check.yaml

Added a process to `cat /logs/*` when a rule parsing error occurs :)

display rule parse error log in console when rule parse error

---

.github/workflows/rule-parse-error-check.yaml

Added a process to `cat /logs/*` when a rule parsing error occurs :)
- Added `check csv-timeline result` step to check which rule is causing the error
I confirmed that actions work as expected with and without errors.
https://github.com/Yamato-Security/hayabusa-rules/actions/runs/8654207238/job/23730955165#step:6:15
https://github.com/Yamato-Security/hayabusa-rules/actions/runs/8654376592/job/23731472288#step:6:15

chg: display error log when rule parse error in Github Actions

---

.github/workflows/update-sigmarule.yaml

Sorry, I forget to add step in `Pipeline for sigma rule updates` ... so I added it.
I confirmed `check csv-timeline result` works as follows.
https://github.com/Yamato-Security/hayabusa-rules/actions/runs/8656500120/job/23737111544#step:9:15

chg: output error log when rule parse error

---

hayabusa/builtin/PowerShell_Op/PwSh_4103_Info_PipelineExecution.yml
hayabusa/builtin/PowerShell_Op/PwSh_4104_Info_ScriptblockLog.yml
hayabusa/builtin/PowerShell_Op/PwSh_4104_Med_ScriptblockLog_PotentiallyMalicious.yml

Fixed a rule where `Channel` was not specified.
When implementing https://github.com/Yamato-Security/hayabusa/issues/1317 , the `Channel` must be specified explicitly.
I confirmed that there is no difference in the number of detections before and after the modification as shown below.
after:
https://github.com/Yamato-Security/hayabusa-rules/actions/runs/8871225497/job/24353898756#step:5:4856
before:
https://github.com/Yamato-Security/hayabusa-rules/actions/runs/8871253258/job/24353962845#step:5:4856

fix: declare `Channel` explicitly

---

.github/workflows/update-sigmarule.yaml

Modified Actions to allow optional selection of branches in the sigma-to-hayabusa-converter repository to test the functionality of branches in sigma-to-hayabusa-converter
Enter the name of the branch to be tested in the sigma-to-hayabusa-converter repository.

feat: add `sigma-to-hayabusa-converter` repo branch checkout option

---

hayabusa/sysmon/Sysmon_1_Info_ProcExec.yml

There was a duplicate key(`sample-evtx`) that has been corrected.
(This is invalid as YAML and will result in a parse error)

Fix: Delete unnecessary duplicate key (`sample-evtx`) in rule

---

scripts/supported_modifiers_check/supported-modifier.py

Fixed to not create a new file when there is no difference in the SupportedSigmaFieldModifiers.md.
```
poetry run python supported-modifier.py ../../../sigma ../../../hayabusa-rules ../../doc/SupportedSigmaFieldModifiers.md
2024-09-06 18:28:34,651 - INFO - Starting script execution: supported-modifier.py
2024-09-06 18:28:34,652 - INFO - Starting to process YAML files in directory: ../../../sigma
2024-09-06 18:28:43,290 - INFO - Finished processing YAML files
2024-09-06 18:28:43,291 - INFO - Starting to process YAML files in directory: ../../../hayabusa-rules
2024-09-06 18:28:56,453 - INFO - Finished processing YAML files
2024-09-06 18:28:56,459 - INFO - No changes detected in the report. Skipping file write.
2024-09-06 18:28:56,459 - INFO - Script execution completed in 21.81 seconds
``` …

chg: If there is no difference, do not create SupportedSigmaFieldModifiers.md

---

doc/SupportedSigmaFieldModifiers.md
scripts/supported_modifiers_check/README.md
scripts/supported_modifiers_check/supported-modifier.py

fix: modify unsupported modifiers

---

config/windash_characters.txt

Right now, the characters for the `windash` modifier are hardcoded but I think this list will expand in the future so I want to be able to dynamically add to this list.

add windash config file

---

hayabusa/builtin/NTFS_Op/NTFS_4_info_volume_mount.yml

Hello!
This PR adds a rule for the event 4 of the channel "Microsoft-Windows-Ntfs/Operational", that tracks mounting of NTFS volumes. Can be useful in correlation with the 'Device Conn' rule to retrieve the volume label / name associated with the device.
Attempt to filter events from normal system usage, but some noise is expected.

Add "NTFS volume mounted" rule

---

hayabusa/builtin/Security/LogonLogoff/OtherLogonLogoffEvents/Sec_4778_Info_RDP-SessReconn.yml
hayabusa/builtin/TerminalServices-LocalSessionManager_Op/LocalSessManager_25_Info_RDS-SessReconn.yml

- Related https://github.com/Yamato-Security/hayabusa/issues/1468
- Added rule for EID:25, which is output when reconnecting to a previous RDP session without logging out.
```
Remote Desktop Services: Session reconnection succeeded:
User: samurai\hayabusa
Session ID: 3
Source Network Address: 203.0.113.1
```
```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event"> 
<System> 
<Provider Name="Microsoft-Windows-TerminalServices-LocalSessionManager" Guid="{5d896912-022d-40aa-a3a8-4fa5515c76d7}" /> 
<EventID>25</EventID> 
<Version>0</Version> 
<Level>4</Level> 
<Task>0</Task> 
<Opcode>0</Opcode> 
<Keywords>0x1000000000000000</Keywords> 
<TimeCreated SystemTime="2024-11-03T07:36:59.0226807Z" /> 
<EventRecordID>88</EventRecordID> 
<Correlation …
```

feat: add RDS Session Reconnect rule (EID:25)

---

README-Japanese.md
README.md
config/channel_abbreviations.txt
config/provider_abbreviations.txt

- Added `Microsoft-Windows-TerminalServices-Gateway/Operational` abbreviation
- Related https://github.com/Yamato-Security/hayabusa/issues/1468

chg: add `Microsoft-Windows-TerminalServices-Gateway/Operational` abbreviation

---

hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4625_Med_LogonFail_UserGuessing_Correlation.yml
hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4625_Med_LogonFail_WrongPW_PW-Guessing_Correlation.yml
hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4648_Med_ExplicitLogon_PW-Spray_Correlation.yml

I noticed that if you run Hayabusa with a minimum alert level of say `medium`, then the correlation rules with a level of `medium` will get a parsing error because the referenced rules were set to `informational`
Ex:
```
[WARN] Failed to parse rule. (FilePath : rules/hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4648_Med_ExplicitLogon_PW-Spray_Correlation.yml) The referenced rule was not found: explicit_logon
[WARN] Failed to parse rule. (FilePath : rules/hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4625_Med_LogonFail_UserGuessing_Correlation.yml) The referenced rule was not found: non_existent_user
[WARN] Failed to parse rule. (FilePath : rules/hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4625_Med_LogonFail_WrongPW_PW-Guessing_Correlation.yml) The referenced rule was not found: …
```

make the levels consistent for correlation referenced rules

---

doc/SupportedSigmaFieldModifiers.md
scripts/supported_modifiers_check/supported-modifier.py

Added `contains|cased`, `startswith|cased`, `endswith|cased` to markdown.
- https://github.com/Yamato-Security/sigma-to-hayabusa-converter/pull/30#issuecomment-2502102250
```
fukusuke@fukusukenoMacBook-Air supported_modifiers_check % poetry run python supported-modifier.py ../../../sigma ../../../hayabusa-rules ../../doc/SupportedSigmaFieldModifiers.md
2024-11-27 08:48:03,252 - INFO - Starting script execution: supported-modifier.py
2024-11-27 08:48:03,253 - INFO - Starting to process YAML files in directory: ../../../sigma
2024-11-27 08:48:11,902 - INFO - Finished processing YAML files
2024-11-27 08:48:11,903 - INFO - Starting to process YAML files in directory: ../../../hayabusa-rules
2024-11-27 08:48:25,107 - INFO - Finished processing YAML files
2024-11-27 08:48:25,114 - INFO - …
```

chg: add supported modifier (`contains|cased`, `startswith|cased`, `endswith|cased`)

---

.github/workflows/supported_modifier.yaml

Closed #812 
I confirmed fixed actions create PR successfully as follows.
https://github.com/Yamato-Security/hayabusa-rules/actions/runs/13052809273
https://github.com/Yamato-Security/hayabusa-rules/pull/813

fix: specify ubuntu 22.04 explicitly in GitHub Actions updateMarkDown

---

config/level_tuning.txt

I found id typo so I fixed it!
https://github.com/Yamato-Security/hayabusa-rules/blob/509246a457d8f7be687b534e48616fd62e7828f1/sigma/builtin/application/msiinstaller/win_builtin_remove_application.yml#L1-L5

fix: level-tuning id 

---

config/data_mapping/Security_4719_AuditPolicyChanged.yaml

I added data mapping for Sec 4719 audit policy changed.
Before (`./target/release/hayabusa csv-timeline -d ../hayabusa-sample-evtx -w --include-eid 4719`):
`2021-10-26 03:30:36.515 +09:00 · Windows Event Auditing Disabled · med · FS03.offsec.lan · Sec · 4719 · 109475 · User: admmig ¦ AuditPolicyChanges: %%8448, %%8450 ¦ CategoryId: %%8280 ¦ SubcategoryGuid: 0CCE9241-69AE-11D9-BED3-505054503030 ¦ SubcategoryId: %%14338 ¦ LID: 0x123550 · SubjectDomainName: OFFSEC ¦ SubjectUserSid: S-1-5-21-4230534742-2542757381-3142984815-1111 · 83d7b3c2-220e-60e8-4aad-98e206e841ba`
After (`./target/release/hayabusa csv-timeline -d ../hayabusa-sample-evtx -w --include-eid 4719 -c ../hayabusa-rules/config`): 
`2021-10-26 03:30:36.515 +09:00 · Windows Event Auditing Disabled · med · FS03.offsec.lan · Sec · …

add sec 4719 data mapping

---

hayabusa/builtin/System/Sys_6013_Info_ComputerUpTime.yml

- Related https://github.com/Yamato-Security/takajo/issues/234
- Related https://github.com/Yamato-Security/hayabusa/issues/1638
```
% ./hayabusa csv-timeline -d ../data/hayabusa-sample-evtx-main -r ~/Scripts/Python/hayabusa-rules/hayabusa/builtin/System/Sys_6013_Info_ComputerUpTime.yml -w -q
Start time: 2025/03/28 07:48
Total event log files: 598
Total file size: 139.2 MB
Loading detection rules. Please wait.
Test rules: 1 (100.00%)
Expand rules: 0 (0.00%)
Enabled expand rules: 0 (0.00%)
Hayabusa rules: 1
Total detection rules: 1
Creating the channel filter. Please wait.
Evtx files loaded after channel filter: 19
Detection rules enabled after channel filter: 1
Output profile: standard
Scanning in progress. Please wait.
Timestamp · RuleTitle · Level · Computer · Channel · EventID · …
```

feat: add System 6013 uptime/timezone rule

---

hayabusa/builtin/DNS-Server/DNS-ServerAnalytical_260_Info_DNS-Request.yml
hayabusa/builtin/DNS-Server/DNS-ServerAnalytical_261_Info_DNS-Response.yml
hayabusa/builtin/DriverFrameworks_UserMode_Op/DvrFmwk_2003_Info_USB-PluggedIn.yml
hayabusa/builtin/NTFS_Op/NTFS_4_info_volume_mount.yml
hayabusa/builtin/PowerShellClassic/PwShClassic_400_Info_PwShEngineStarted.yml
hayabusa/builtin/PowerShellClassic/PwShClassic_400_Med_PwShStarted_V2DowngradeAttack.yml
hayabusa/builtin/PowerShell_Op/PwSh_4103_Info_PipelineExecution.yml
hayabusa/builtin/PowerShell_Op/PwSh_4104_Info_ScriptblockLog.yml
hayabusa/builtin/PowerShell_Op/PwSh_4104_Med_ScriptblockLog_PotentiallyMalicious.yml
hayabusa/builtin/TerminalServices-LocalSessionManager_Op/LocalSessManager_21_Info_RDP-Logon.yml
hayabusa/builtin/TerminalServices-LocalSessionManager_Op/LocalSessManager_22_Info_RDP-SessStart_Noisy.yml
hayabusa/builtin/TerminalServices-LocalSessionManager_Op/LocalSessManager_23_Info_RDP-Logoff.yml
hayabusa/builtin/TerminalServices-LocalSessionManager_Op/LocalSessManager_24_Info_RDP-Disconnect.yml
hayabusa/builtin/TerminalServices-LocalSessionManager_Op/LocalSessManager_25_Info_RDP-Reconnect.yml

Since the following feature refers to the service and category fields, I added these fields to the Hayabusa rules where they were not explicitly declared.
- https://github.com/Yamato-Security/WELA-RulesGenerator/pull/2
- https://fukusuket-eventlog-baseline-guide-streamlit-app-cty7uv.streamlit.app/
The Sigma specification was referenced from the following document.
- https://github.com/Yamato-Security/sigma-to-hayabusa-converter?tab=readme-ov-file#about-the-logsource-field
- https://github.com/SigmaHQ/sigma-specification/blob/main/specification/sigma-rules-specification.md#logsource
- https://github.com/SigmaHQ/sigma-specification/blob/main/appendix/sigma-taxonomy-appendix.md

chg: add logsource:service/category

---

config/channel_abbreviations.txt

This pull request fixes the RDPClient channel abbreviation. It is currently set to "RDP-Client", but since the generic abbreviations file contains the abbrevation "Cli" for "Client", Hayabusa timeline actually uses "RDP-Cli" instead.
- Changed abbreviation from "RDP-Client" to "RDP-Cli" at the end of line 21
1. Pull the branch "bugfix/fix-rdp-client-channel-abbreviation".
2. Run Hayabusa csv-timeline
3. Notice that the RDPClient channel abbrevation is "RDP-Cli" before and after this change.
- Full name of the RDPClient channel: Microsoft-Windows-TerminalServices-RDPClient/Operational
- Path of the channel abbreviations file: ./config/channel_abbreviations.txt
- Path of the generic abbreviations file: ./config/generic_abbreviations.txt
Thank you and have a nice day :)

Fix RDPClient channel abbreviation
