hayabusa/default/alerts/System/7045_CreateOrModiftySystemProcess-WindowsService_MaliciousServiceInstalled.yml, hayabusa/non-default/alerts/Security/4688_SuspiciousCommandLine-PossibleLOLBIN-Abuse.yml
=> updated regex path

config/eventkey_alias.txt, hayabusa/non-default/events/Security/4688_ProcessCreationWithCommandLine.yml, hayabusa/non-default/events/Security/4688_ProcessCreationWithoutCommandLine.yml
Fixed https://github.com/Yamato-Security/hayabusa/issues/416
=> Fix 4688 rule CommandLine bug

tools/sigmac/test_files/expected_rules/test_rules/test0001.yml, tools/sigmac/test_files/expected_rules/test_rules/test0002.yml, tools/sigmac/test_files/expected_rules/test_rules/test0003.yml, tools/sigmac/test_files/expected_rules/test_rules/test0004.yml, tools/sigmac/test_files/expected_rules/test_rules/test0005.yml, tools/sigmac/test_files/expected_rules/test_rules/test0006.yml, tools/sigmac/test_files/expected_rules/test_rules/test0007.yml, tools/sigmac/test_files/expected_rules/test_rules/test0008.yml, tools/sigmac/test_files/expected_rules/test_rules/test0009.yml, tools/sigmac/test_files/expected_rules/test_rules/test0010.yml, tools/sigmac/test_files/expected_rules/test_rules/test0011.yml, tools/sigmac/test_files/expected_rules/test_rules/test0012.yml, tools/sigmac/test_files/expected_rules/test_rules/test0013.yml, tools/sigmac/test_files/expected_rules/test_rules/test0014.yml, tools/sigmac/test_files/expected_rules/test_rules/test0015.yml, tools/sigmac/test_files/expected_rules/test_rules/test0016.yml, tools/sigmac/test_files/expected_rules/test_rules/test0017.yml, tools/sigmac/test_files/expected_rules/test_rules/test0018.yml, tools/sigmac/test_files/expected_rules/test_rules/test0019.yml, tools/sigmac/test_files/expected_rules/test_rules/test0020.yml, tools/sigmac/test_files/expected_rules/test_rules/test0021.yml, tools/sigmac/test_files/expected_rules/test_rules/test0022.yml
closed #32 
- changed ruletype in expected rule yaml files  from SIGMA to Test
=> Changed expected rule test type#32

hayabusa/default/alerts/Security/4720_CreateAccount-LocalAccount_UserAccountCreated.yml
=> fix a typo

sigma/builtin/bits_client/win_bits_client_susp_local_file.yml, sigma/builtin/bits_client/win_bits_client_susp_powershell_job.yml, sigma/builtin/bits_client/win_bits_client_susp_use_bitsadmin.yml
@hitenkoku 
sigmaへのご連絡とPR対応ありがとうございました！
取り敢えずこちらの方でもChannelを直しておきます。
=> bits client channel fix

README-Japanese.md, README.md
=> Twitter broken link fix

hayabusa/sysmon/alerts/6_DriverLoaded_UnknownSignature.yml
https://github.com/Yamato-Security/hayabusa/issues/493 が直るはずです。多分。
=> fix sysmon buggy rule

.github/workflows/update-sigmarule.yaml
DevelopCloseに向けてGithubActions止め
=> Add: stop github actions

config/eventkey_alias.txt
=> fix version alias

README-Japanese.md, README.md
hayabusa rules readmeを更新しました。ご確認ください。
=> update readme section multiple data fields

tools/sigmac/convert.py
closes #95 
Hayabusaルールに変換できないSigmaルールの変換時WARNINGを抑制するオプションの追加。
SIGMAルール側の問題で正常に変換できないルールを見つけるためにこのオプションを利用して非対応WARNINGを表示させないことで見つけやすくする
```
❯ python3 convert.py -r rules/windows.bak --suppression
```
```
❯ python3 convert.py -r rules/windows.bak
Converting rules. Please wait.
[WARNING ] Conversion of "haaybusa_convert_failed.yml" failed.
command: ['python3', './tools/sigmac', '-t', 'hayabusa', '-c', './tools/config/generic/sysmon.yml', '-c', './tools/config/generic/windows-services.yml', '--defer-abort', 'rules/windows.bak/failed/haaybusa_convert_failed.yml']
An unsupported feature is required for this Sigma rule (rules/windows.bak/failed/haaybusa_convert_failed.yml): This rule contains aggregation operator not implemented for this backend
98 rules where converted! (failed: 1)
❯ python3 …
```
=> Add: error suppression option

.github/workflows/update-sigmarule.yaml
close #96 
とりあえず、workflow fileが使えるように修正してみました。ただ、PR作ってマージする部分は試せてないです。多分このままだと試せないので、一旦承認して動かしてみるか無いかもしれません。
`schedule`以外に`workflow_dispatch`というのを指定しているので、一旦承認したらGitHubのWEBUIのActionタブからこのactionをいつでも実行できるようになっているはずです。
=> update sigmarule githubaction

.github/.kodiak.toml, README-Japanese.md, README.md
auto approve any PRs from github-actions
=> add auto approve kodiak app

README-Japanese.md
[EnableWindowsLogSettings](https://github.com/Yamato-Security/EnableWindowsLogSettings)と[Hayabusa](https://github.com/Yamato-Security/hayabusa/blob/main/README-Japanese.md)の説明が逆だったので、修正しました。
=> fix readme japanese

config/channel_abbreviations.txt, config/eventkey_alias.txt, hayabusa/builtin/System/Sys_104_High_SysLogCleared.yml, hayabusa/builtin/System/Sys_6005_Info_EventLogSvcStarted.yml, hayabusa/builtin/System/Sys_6006_Info_EventLogSvcStopped.yml, hayabusa/builtin/TerminalServices-LocalSessionManager_Op/LocalSessManager_21_Info_RDS-SessLogon.yml, hayabusa/builtin/TerminalServices-LocalSessionManager_Op/LocalSessManager_22_Info_RDS-SessStart.yml, hayabusa/builtin/TerminalServices-LocalSessionManager_Op/LocalSessManager_23_Info_RDS-SessLogoff.yml, hayabusa/builtin/TerminalServices-LocalSessionManager_Op/LocalSessManager_24_Info_RDS-SessDisconn.yml, hayabusa/builtin/TerminalServices-RDPClient_Op/RDP-Client_1102_Info_ConnAttempt.yml, hayabusa/builtin/TerminalServices-RemoteConnectionManager_Op/RemoteConnManger_1149_Info_RDS-Logon.yml, hayabusa/builtin/TerminalServices-RemoteConnectionManager_Op/RemoteConnManger_261_Info_RDS-Conn.yml
=> Add RDS rules

config/default_details.txt
- Fixed typo in default_details.txt
=> Fixed detault details typo

config/geoip_field_mapping.yaml
New config file for SrcIP and TgtIP field mapping.
=> Add geoip field mapping config file

config/channel_eid_info.txt, config/geoip_field_mapping.yaml
Updated geoip config. also slightly updated channel eid info
=> update geoip config

config/channel_abbreviations_generic.txt
added channel generic name shorter list.
refs: 
- https://github.com/Yamato-Security/hayabusa/issues/923
- https://github.com/Yamato-Security/hayabusa/pull/927
=> feat: added channel generic name shorter list

hayabusa/builtin/System/Sys_7045_High_ServiceInstalled_SuspiciousService.yml, hayabusa/builtin/WMI-Activity_Op/WMI_5861_Med_FilterToConsumerBinding_CmdExec.yml
I changed the syntax of these two rules to make them easier to read and use as examples for rules with multiple OR conditions.
=> make contains fields easier to read

config/exclude_rules.txt
Good morning!
Can one of you check this?
=> exclude rules that use near

config/eventkey_alias.txt, hayabusa/builtin/WindowsDefender/Defender_1116_Crit_Alert.yml, hayabusa/builtin/WindowsDefender/Defender_1116_High_Alert.yml, hayabusa/builtin/WindowsDefender/Defender_1116_Low_Alert.yml, hayabusa/builtin/WindowsDefender/Defender_1116_Med_Alert.yml
- Fix: #349
- Changed detection rule of Windows Defender malware detection event ID 1116
- Check  `Severity ID` instead of `Severity Name`
- Added event_key alias for `Severity ID`
- Hard: Macbook Air(M1, 2020) , Memory 8GB, Core 8
`Defender Alert (Severe) (1) ` rule detected `Severity ID` == 5 eventlog as follows.
``` 
fukusuke@fukusukenoAir hayabusa-2.3.2-all-platforms % ./hayabusa-2.3.2-mac-arm csv-timeline -f ../Microsoft-Windows-Windows\ Defender%4Operational.evtx -r ./rules/hayabusa/builtin/WindowsDefender -p super-verbose
╔╗ ╔╦═══╦╗  ╔╦═══╦══╗╔╗ ╔╦═══╦═══╗
║║ ║║╔═╗║╚╗╔╝║╔═╗║╔╗║║║ ║║╔═╗║╔═╗║
║╚═╝║║ ║╠╗╚╝╔╣║ ║║╚╝╚╣║ ║║╚══╣║ ║║
║╔═╗║╚═╝║╚╗╔╝║╚═╝║╔═╗║║ ║╠══╗║╚═╝║
║║ ║║╔═╗║ ║║ ║╔═╗║╚═╝║╚═╝║╚═╝║╔═╗║
╚╝ ╚╩╝ ╚╝ ╚╝ ╚╝ ╚╩═══╩═══╩═══╩╝ ╚╝
by Yamato Security …
```
=> chg: check  Windows Defender malware detection `SeverityID` instead of `SeverityName`

config/channel_abbreviations.txt, config/default_details.txt, hayabusa/builtin/PowerShell_Op/PwSh_4103_Info_PipelineExecution.yml, hayabusa/builtin/PowerShell_Op/PwSh_4104_Info_ScriptblockLog.yml, hayabusa/builtin/PowerShell_Op/PwSh_4104_Med_ScriptblockLog_PotentiallyMalicious.yml
added support for powershellcore
=> support powershellcore

config/logsource-mapping.yml, tools/sigmac/logsource-mapping.yml
I added a single easier to use YML file for `logsource` conversion.
=> add logsource mapping yml file

config/channel_eid_info.txt
I removed periods from the event titles to reduce a little space. Could you check?
=> remove period from event titles

tools/sigmac/convert.py
Supports folder structure after [Sigma#4191](https://github.com/SigmaHQ/sigma/pull/4191) update.(`convert.py`)
- As before, the root directories are following two.
- `sigma/builtin`
- `sigma/sysmon`
- and new folder's rule are located following folder
- `rules-compliance` -> `compliance`(Currently 0 rules)
- `rules-dfir` -> `dfir`(Currently 0 rules)
- `rules-emerging-threats` -> `emerging-threats`
- `rules-placeholder/windows` -> `placeholder`
- `rules-threat-hunting` -> `threat-hunting`(Currently 0 rules)
- `deprecated/windows` -> `deprecated`
- `unsuppoerted` -> `unsupported`
- Hard: Macbook Air(M1, 2020) , Memory 8GB, Core 8
`convert.py` was executed successfully as follows.
```
fukusuke@fukusukenoAir sigma % python3 convert.py --debug --verbose
... …
```
=> fix: Support folder structure after Sigma #4191 update

config/default_details.txt, config/eventkey_alias.txt, config/exclude_rules.txt, config/pivot_keywords.txt
I added the pivot_keywords.txt config file here so that I can update it more frequently.
@hitenkoku Could you check?
=> Add pivot keywords.txt

hayabusa/builtin/VHDMP_Op/VHDMP_12_Info_ISO-Mount.yml, hayabusa/builtin/VHDMP_Op/VHDMP_12_Info_VHD-Mount.yml, hayabusa/builtin/VHDMP_Op/VHDMP_12_Info_VHDX-Mount.yml
I added rules to detect ISO and VHD mounting.
=> Added rules to detect ISO mounting

config/default_details.txt, hayabusa/sysmon/Sysmon_10_High_ProcessAccess_RuleAlert.yml, hayabusa/sysmon/Sysmon_11_Med_FileCreated_RuleAlert.yml, hayabusa/sysmon/Sysmon_12_Med_RegKeyCreateDelete_RuleAlert.yml, hayabusa/sysmon/Sysmon_13_RegKeyValueSet_RuleAlert.yml, hayabusa/sysmon/Sysmon_15_ADS-Created_RuleAlert.yml, hayabusa/sysmon/Sysmon_17_PipeCreated_RuleAlert.yml, hayabusa/sysmon/Sysmon_18_PipeConn_RuleAlert.yml, hayabusa/sysmon/Sysmon_19_WmiEventFilterActivity_RuleAlert.yml, hayabusa/sysmon/Sysmon_1_High_ProcExec_RuleAlert.yml, hayabusa/sysmon/Sysmon_20_Med_WmiEventConsumerActivity_RuleAlert.yml, hayabusa/sysmon/Sysmon_21_Med_WmiEventConsumerToFilterActivity_RuleAlert.yml, hayabusa/sysmon/Sysmon_22_Med_DNS-Query_RuleAlert.yml, hayabusa/sysmon/Sysmon_23_Med_DeletedFileArchived_RuleAlert.yml, hayabusa/sysmon/Sysmon_24_Med_ClipboardChange_RuleAlert.yml, hayabusa/sysmon/Sysmon_26_Med_FileDeleted_RuleAlert.yml, hayabusa/sysmon/Sysmon_3_Med_NetConn_RuleAlert.yml, hayabusa/sysmon/Sysmon_7_Low_ImgLoaded_RuleAlert.yml, hayabusa/sysmon/Sysmon_8_High_ProcInj_RuleAlert.yml
closes https://github.com/Yamato-Security/hayabusa-rules/issues/402
Could you check this?
=> update sysmon default details

tools/sigmac/windows-services.yaml
I added these 2 new services because of the sigma rules I added here: https://github.com/SigmaHQ/sigma/pull/4234/files/d8ba530ee407c3116e3026b2abba96798123f82a..de9f3a35216965596c8a9863d0057bdb30a0152b
=> add capi2 and CSclientlifecycle services

README-Japanese.md, README.md
=> Add '|all'  field explanation

config/exclude_rules.txt, hayabusa/sysmon/Sysmon_28_High_FileBlockShredding.yml, hayabusa/sysmon/Sysmon_29_Info_FileExecutableDetected.yml
I updated the exclude rules and added rules for new sysmon events.
=> updated exclude rules and new sysmon events

hayabusa/sysmon/Sysmon_1_Low_ExeFileRenamed.yml
- Fix #526
- added escape for `?`
- OS: macOS sonoma version 14.0
I confirmed that the following 6 cases were detected using the hayabusa-sample-evtx data.
`% ./hayabusa csv-timeline -d ../hayabusa-sample-evtx -o new.csv -C -D -n -u --debug -w -r test.yml`
```
"Timestamp","Computer","Channel","EventID","Level","RecordID","RuleTitle","Details","ExtraFieldInfo"
"2020-04-26 07:19:28.080 +09:00","MSEDGEWIN10","Sysmon",1,"low",27636,"Renamed Exe File","Cmdline: c:\Program Files\vulnsvc\mmm.exe ¦ Proc: C:\program.exe ¦ User: NT AUTHORITY\SYSTEM ¦ ParentCmdline: C:\Windows\system32\services.exe ¦ LID: 0x3e7 ¦ LGUID: 747F3D96-B764-5EA4-0000-0020E7030000 ¦ PID: 2856 ¦ PGUID: 747F3D96-B766-5EA4-0000-0010E7880100 ¦ ParentPID: 584 ¦ ParentPGUID: …
```
=> fix: add escape for `?`

hayabusa/builtin/PowerShellClassic/PwShClassic_400_Info_PwShEngineStarted.yml
- feat #512
- added PowerShell Classic EID 400 rule.
- exclude https://github.com/Yamato-Security/hayabusa-rules/issues/512#issuecomment-1793683201 pattern
- OS: macOS sonoma version 14.0
csv-timeline
```
"Timestamp","Computer","Channel","EventID","Level","RecordID","RuleTitle","Details","ExtraFieldInfo"
"2021-01-28 18:58:44.538 +09:00","DESKTOP-ST69BPO","PwShClassic",400,"info",711,"PwSh Engine Started","Data: Available ¦ Data: NewEngineState=Available PreviousEngineState=None SequenceNumber=13 HostName=ConsoleHost HostVersion=5.1.18362.145 HostId=64821494-0737-4ce9-ad67-3ac0e50a81b8 HostApplication=powershell calc EngineVersion=5.1.18362.145 RunspaceId=74ae21ca-7fa9-40cc-a265-7a41fdb168a6 PipelineId= CommandName= CommandType= …
```
=> feat: add PowerShell Classic EID:400 rule

hayabusa/builtin/PowerShellClassic/PwShClassic_400_Info_PwShEngineStarted.yml
- Added `details: 'HostApplication: %HostApplication%'` 
- OS: macOS sonoma version 14.0
csv-timeline
```
"Timestamp","Computer","Channel","EventID","Level","RecordID","RuleTitle","Details","ExtraFieldInfo"
"2023-10-12 16:29:06.591 +09:00","MyComputer","PwShClassic",400,"info",7,"PwSh Engine Started","HostApplication: powershell -ExecutionPolicy Bypass -windowstyle hidden -command C:\mcj\tool\win10\ssd_fw_update\ssd_fw_update.ps1","CommandLine: ¦ CommandName: ¦ CommandPath: ¦ CommandType: ¦ Data: Available ¦ Data: NewEngineState=Available PreviousEngineState=None SequenceNumber=13 HostName=ConsoleHost HostVersion=5.1.22621.1778 HostId=bafb59f7-0327-4c95-9b52-e515e2c033ff HostApplication=powershell -ExecutionPolicy Bypass -windowstyle …
```
=> feat: add detail PowerShellClassic 

hayabusa/builtin/System/Sys_6009_Info_ComputerStartup.yml
I added the system 6009 rule to identify OS version information.
=> Add System 6009 rule

hayabusa/builtin/UnkwnChannEID_Med_PossibleHiddenShellcode.yml
- Fixd #598 
I confirmed it using the following steps.
https://github.com/Yamato-Security/hayabusa-rules/issues/598#issue-2120739233
```json
{
"Timestamp": "2022-02-07 19:55:00.116 +09:00",
"Computer": "DESKTOP-A8CALR3",
"Channel": "MS-Win-Storage-Storport/Op",
"EventID": 534,
"Level": "med",
"RecordID": 9,
"RuleTitle": "Possible Hidden Shellcode",
"Details": {
"Data": "02000000B000000031E01000000000001600000000010000080028020000000058425253010000009000000002000000C00000000000000000000000020000001E000000000000000000000080000000000000003D000000807CF7B58191FFFF000000000000000070873FB18191FFFF0000000000000000202060B68191FFFF402460B68191FFFF0000000000000000000000000000000000000000000000000000000000000000FF41040000000000"
},
"ExtraFieldInfo": {
"AdapterGuid": …
```
=> fix: add details key string

.github/workflows/update-sigmarule.yaml
Sorry! This file also needed an update😅
=> fix: update hayabusa zip name

config/default_details.txt, hayabusa/builtin/Crypto-DPAPI_Debug/CryptoDPAPI_16385_Info_DPAPI-Access.yml, hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4625_Med_LogonFail_WrongPW_PW-Guessing_Cnt.yml, hayabusa/builtin/Security/System/SecuritySystemExtension/Sec_4611_High_AbnormalLogonProcessRegisteredWithLSA.yml, hayabusa/builtin/Security/System/SecuritySystemExtension/Sec_4611_Info_LogonProcessRegisteredWithLSA.yml
I just added a couple of hayabusa rules to use with new takajo commands.
=> Sec4611 and DPAPI rules

hayabusa/builtin/TerminalServices-Gateway_Op/RDS_Gateway_Disconnect.yml, hayabusa/builtin/TerminalServices-Gateway_Op/RDS_Gateway_Logon.yml
Informational rule for RDS Gateway logon and disconnect, note alias hasn't been created to specify detail fields, hence default selected.
=> RDS_Gateway rules

doc/SupportedSigmaFieldModifiers.md, scripts/supported_modifiers_check/supported-modifier.py
Do not update `SupportedSigmaFieldModifiers.md` when there are no updates
=> fix: Do not update `SupportedSigmaFieldModifiers.md` when there are no updates

doc/SupportedSigmaFieldModifiers.md, scripts/supported_modifiers_check/supported-modifier.py
Closed #750 
```
% poetry run python supported-modifier.py ../../../sigma ../../../hayabusa-rules ../../doc/SupportedSigmaFieldModifiers.md
2024-10-18 21:25:31,677 - INFO - Starting script execution: supported-modifier.py
2024-10-18 21:25:31,678 - INFO - Starting to process YAML files in directory: ../../../sigma
2024-10-18 21:25:40,305 - INFO - Finished processing YAML files
2024-10-18 21:25:40,307 - INFO - Starting to process YAML files in directory: ../../../hayabusa-rules
2024-10-18 21:25:53,397 - INFO - Finished processing YAML files
2024-10-18 21:25:53,404 - INFO - Markdown report generated and saved to ../../doc/SupportedSigmaFieldModifiers.md
2024-10-18 21:25:53,404 - INFO - Script execution completed in 21.73 seconds
```
outputted markdown
```
| Field Modifier        |   Sigma …
```
=> feat: Add correlation rules support tables to SupportedSigmaFieldModifiers.md

.github/workflows/rule-parse-error-check.yaml, .github/workflows/update-sigmarule.yaml
Closed #756 
https://github.com/Yamato-Security/hayabusa-rules/actions/runs/11535921181
=> fix: changed GitHub Action's linux package name

config/eventkey_alias.txt, hayabusa/builtin/TerminalServices-Gateway_Op/RDS_Gateway_302_Info_LogonSuccess.yml, hayabusa/builtin/TerminalServices-Gateway_Op/RDS_Gateway_302_Low_LogonError.yml, hayabusa/builtin/TerminalServices-Gateway_Op/RDS_Gateway_303_Info_Logoff.yml
I updated the RDS GTW rules because it wasn't displaying field info in `details`
=> udpate rds gtw rules

.github/workflows/update-sigmarule.yaml
v3 will be deprecated soon so I updated to v4
=> update actions to v4

config/exclude_rules.txt, hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4648_Med_ExplicitLogon_PW-Spray_Correlation.yml
I noticed some FPs so I fixed them. (Ignoring some older rules for now)
=> lessen FPs

config/closing_messages.txt, config/opening_messages.txt
I added two message files to be used for Hayabusa to output in the beginning and end. I will create an issue in the Hayabusa repository later for outputting these messages randomly.
=> add opening and closing messages

hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4624_Info_Logon-Type-10-RemoteInteractive.yml
I found a minor typo and fixed it!
=> fix typo in Sec_4624_Info_Logon-Type-10-RemoteInteractive.yml

config/default_details.txt
I made a mistake. These fields should be target user fields instead of source.
=> update RDP target log field

doc/SupportedSigmaFieldModifiers.md, scripts/supported_modifiers_check/supported-modifier.py
Modifiers to be added support in version 3.0.0 are now output to markdown!
=> chg: update supported modifier in supported-modifier.py

hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4624_Info_Logon-Type-5-Service.yml, hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4624_Info_Logon-Type-5-Service_Noisy.yml
I found a typo in the LEVEL and fixed it!
=> fix: level typo

config/level_tuning.txt, config/opening_messages.txt
I updated the level tuning config
=> update level tuning config

config/data_mapping/Security_4674_ObjectAccessAttempt.yaml
I updated some codes that were not being translated.
=> updated AccessMask codes

hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4648_Info_ExplicitLogon.yml, hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4648_Info_ExplicitLogon_Noisy.yml, hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4648_Med_ExplicitLogon_SuspProc.yml
I updated the title and description for explicit logons
=> update rule title and description

README-Japanese.md, README.md, hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4624_Info_Logon-Type-10-RemoteInteractive.yml
I found logsource missing rule and fixed it!
=> fix: add missing logsource block

doc/SupportedSigmaFieldModifiers.md, scripts/supported_modifiers_check/supported-modifier.py
The cause was that a YAML file was added to the tests folder in the following pull request. So I ignore it!
- https://github.com/SigmaHQ/sigma/pull/5394
=> fix : supported modifier update

.github/workflows/rule-parse-error-check.yaml, .github/workflows/update-sigmarule.yaml
Add Slack notification on failure!
- https://github.com/Yamato-Security/hayabusa-rules/actions/runs/16854670882
=> feat: add slack notification 

doc/SupportedSigmaFieldModifiers.md, scripts/supported_modifiers_check/supported-modifier.py
=> Add base64 to SupportedSigmaModifier.md
